import numpy as np


def augmentTabular0(md, y=None, noise_std=0.1):
	md.X_augmented = md.X


def aitchisonPerturbation(md, noise_scale=0.1, noise_type='uniform'):
	"""
	Apply Aitchison perturbations to CLR-transformed data.

	Args:
		data: numpy array (n_samples, n_features)
		noise_scale: max absolute perturbation magnitude
		noise_type: 'uniform' or 'laplace'
	Returns:
		perturbed data (same shape)
	"""
	if noise_type == 'uniform':
		noise = np.random.uniform(-noise_scale, noise_scale, md.X.shape)
	elif noise_type == 'laplace':
		noise = np.random.laplace(0, noise_scale, md.X.shape)
	else:
		raise ValueError("noise_type must be 'uniform' or 'laplace'")

	md.X_augmented = md.X + noise


def augmentTabular1(md, y=None, noise_std=0.1):
	X_augmented = md.X.copy()
	for col in range(md.X.shape[1]):
		X_augmented[:, col] += np.random.normal(
			0,
			noise_std * md.X[:, col].std(),  # Scale noise by feature std
			size=md.X.shape[0]
		)
	md.X_augmented = X_augmented



def augmentTabular2(md, y=None, noise_std=0.1):
# Create copy of input data
	md.X_augmented = md.X.copy()

	numeric_mask = np.isfinite(md.X).all(axis=0)
	if numeric_mask.any():
		md.X_augmented[:, numeric_mask] += np.random.normal(
			0,
			noise_std * np.std(md.X[:, numeric_mask], axis=0),
			size=md.X.shape
		)


def augmentTabular_pandas (md, y=None, noise_std=0.1, flip_cat_prob=0.05):
	md.X_aug = md.X_unlab.copy()

	# Gaussian noise for numeric features
	numeric_cols = md.X_unlab.select_dtypes(include=['int64', 'float64']).columns
	md.X_aug[numeric_cols] += np.random.normal(0, noise_std * md.X_unlab[numeric_cols].std(), md.X_unlab.shape)

	# Random flip for categorical (if any)
	if hasattr(md.X_unlab, 'select_dtypes'):
		cat_cols = md.X_unlab.select_dtypes(include=['object', 'category']).columns
		for col in cat_cols:
			mask = np.random.rand(*md.X_unlab.shape) < flip_cat_prob
			md.X_aug.loc[mask, col] = md.X_unlab.loc[mask, col].sample(frac=1).values


"""Applies Compositional CutMix to some training data.
	Args:
		md.X_lab: model inputs
		md.y_lab: model outputs
		factor: the enlargement factor by which to augment X and y.
			If X, y have n rows, the augmented data will have factor * n.
		weight: the total weight of all the augmented data generated.
			For example, if weight=0.5, then all the augmented data will
			weigh the same as all the original training data.
			Typically, this means the synthetic samples are downweighted
			relative to the original data.
		
	Returns:
		X_aug: model inputs including both those from the original
			training data and those generated by data augmentation.
		y_aug: model outputs including both those from the original
			training data and those generated by data augmentation.
		w_aug: sample weights for each sample in X_aug and y_aug.
			Typically, the sample weights corresponding to samples
			from the original training data will have high weight,
			those corresponding to synthetic datapoints will have
			low weight.
"""

def compositionalCutmix(md, factor=2, weight=0.5):
	X = md.X.copy()
	y = md.y.copy()
	w = np.ones_like(y)

	for val in [0]:
		idxs = md.y == val
		X_temp = md.X[idxs, :]
		n = X_temp.shape[0]
		n_aug = int(factor * n - n)

		idx1 = np.random.choice(n, size=n_aug)
		idx2 = np.random.choice(n, size=n_aug)

		p = np.random.rand(n_aug)
		mask = np.random.binomial(1, p, [X_temp.shape[1], n_aug]).T
		X_aug = mask * X_temp[idx1, :] + (1 - mask) * X_temp[idx2, :]

		X_aug = X_aug / X_aug.sum(axis=1, keepdims=True)

		X = np.concatenate([X, X_aug], axis=0)
		y = np.concatenate([y, np.repeat(val, n_aug)])
		w = np.concatenate([w, np.repeat(weight / (1 - weight) * md.X.shape[0] / n_aug, n_aug)])

    # Shuffle data
	n = X.shape[0]
	idx = np.arange(n)
	np.random.shuffle(idx)
    
	md.X = X[idx].copy()
	md.y = y[idx].copy()
	# w[idx]
	# return X[idx], y[idx], w[idx]

	
"""Applies Aitchison Mixup to some training data.
	Args:
		X_train: model inputs
		y_train: model outputs
		factor: the enlargement factor by which to augment X and y.
			If X, y have n rows, the augmented data will have factor * n.
		weight: the total weight of all the augmented data generated.
			For example, if weight=0.5, then all the augmented data will
			weigh the same as all the original training data.
			Typically, this means the synthetic samples are downweighted
			relative to the original data.
		
	Returns:
		X_aug: model inputs including both those from the original
			training data and those generated by data augmentation.
		y_aug: model outputs including both those from the original
			training data and those generated by data augmentation.
		w_aug: sample weights for each sample in X_aug and y_aug.
			Typically, the sample weights corresponding to samples
			from the original training data will have high weight,
			those corresponding to synthetic datapoints will have
			low weight.
"""

def aitchisonMixup(X_train, y_train, factor=10, weight=0.5):

	X = X_train.copy()
	y = y_train.copy()
	w = np.ones_like(y)

	for val in np.unique(y_train):
		idxs = y_train == val
		X_temp = X_train[idxs, :]
		n = X_temp.shape[0]
		n_aug = int(factor * n) - n

		lam = np.random.rand(n_aug).reshape([-1, 1])
		idx1 = np.random.choice(n, size=n_aug)
		idx2 = np.random.choice(n, size=n_aug)

        # Take convex combination
		X_aug = lam * X_temp[idx1, :] + (1 - lam) * X_temp[idx2, :]

		X = np.concatenate([X, X_aug], axis=0)
		y = np.concatenate([y, np.repeat(val, n_aug)])
		w = np.concatenate([w, np.repeat(weight / (1 - weight) * X_train.shape[0] / n_aug, n_aug)])
    
    # Shuffle data
	n = X.shape[0]
	idx = np.arange(n)
	np.random.shuffle(idx)
    
	return X[idx], y[idx], w[idx]

"""Applies Compositional Feature Dropout to some training data.

	Args:
		X_train: model inputs
		y_train: model outputs
		factor: the enlargement factor by which to augment X and y.
			If X, y have n rows, the augmented data will have factor * n.
		weight: the total weight of all the augmented data generated.
			For example, if weight=0.5, then all the augmented data will
			weigh the same as all the original training data.
			Typically, this means the synthetic samples are downweighted
			relative to the original data.
		
	Returns:
		X_aug: model inputs including both those from the original
			training data and those generated by data augmentation.
		y_aug: model outputs including both those from the original
			training data and those generated by data augmentation.
		w_aug: sample weights for each sample in X_aug and y_aug.
			Typically, the sample weights corresponding to samples
			from the original training data will have high weight,
			those corresponding to synthetic datapoints will have
			low weight.
"""

def compositionalFeatureDropout(X_train, y_train, factor=10, weight=0.5):
	X = X_train.copy()
	y = y_train.copy()
	w = np.ones_like(y)

	for val in [0, 1]:
		idxs = y_train == val
		X_temp = X_train[idxs, :]
		n = X_temp.shape[0]
		n_aug = int(factor * n) - n
		X_aug = []
		y_aug = []
		p = np.random.rand(n_aug)
		idx = np.random.choice(n, size= n_aug)
		mask = np.random.binomial(1, p, [X_temp.shape[1], n_aug]).T
		X_new = X_temp[idx, :].copy()
		X_new[mask.astype('bool')] = 1
		X_aug.append(X_new)
		y_aug.append(y_train[idx])
		X_aug = X_new
		y_aug = y_aug
		X = np.concatenate([X, X_aug], axis=0)
		y = np.concatenate([y, np.repeat(val, n_aug)])
		w = np.concatenate([w, np.repeat(weight / (1 - weight) * X_train.shape[0] / n_aug, n_aug)])

    # Shuffle data
	n = X.shape[0]
	idx = np.arange(n)
	np.random.shuffle(idx)

	return X[idx], y[idx], w[idx]

